-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cpu is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mem_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    mem_ce0 : OUT STD_LOGIC;
    mem_we0 : OUT STD_LOGIC;
    mem_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mem_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    pstrb : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of cpu is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "cpu_cpu,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7z010-clg225-1I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.667000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=467,HLS_SYN_LUT=1709,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_file_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal reg_file_ce0 : STD_LOGIC;
    signal reg_file_we0 : STD_LOGIC;
    signal reg_file_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_file_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_file_ce1 : STD_LOGIC;
    signal reg_file_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start : STD_LOGIC;
    signal grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done : STD_LOGIC;
    signal grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_idle : STD_LOGIC;
    signal grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_ready : STD_LOGIC;
    signal grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_ce0 : STD_LOGIC;
    signal grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_we0 : STD_LOGIC;
    signal grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start : STD_LOGIC;
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done : STD_LOGIC;
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_idle : STD_LOGIC;
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_ready : STD_LOGIC;
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_ce0 : STD_LOGIC;
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_we0 : STD_LOGIC;
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce0 : STD_LOGIC;
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_we0 : STD_LOGIC;
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce1 : STD_LOGIC;
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb_ap_vld : STD_LOGIC;
    signal grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal pstrb_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cpu_cpu_Pipeline_VITIS_LOOP_22_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        reg_file_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        reg_file_ce0 : OUT STD_LOGIC;
        reg_file_we0 : OUT STD_LOGIC;
        reg_file_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component cpu_cpu_Pipeline_PROGRAM_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mem_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        mem_ce0 : OUT STD_LOGIC;
        mem_we0 : OUT STD_LOGIC;
        mem_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mem_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        reg_file_ce0 : OUT STD_LOGIC;
        reg_file_we0 : OUT STD_LOGIC;
        reg_file_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        reg_file_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        reg_file_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        reg_file_ce1 : OUT STD_LOGIC;
        reg_file_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        pstrb : OUT STD_LOGIC_VECTOR (3 downto 0);
        pstrb_ap_vld : OUT STD_LOGIC );
    end component;


    component cpu_reg_file_RAM_1WNR_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    reg_file_U : component cpu_reg_file_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => reg_file_address0,
        ce0 => reg_file_ce0,
        we0 => reg_file_we0,
        d0 => reg_file_d0,
        q0 => reg_file_q0,
        address1 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address1,
        ce1 => reg_file_ce1,
        q1 => reg_file_q1);

    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32 : component cpu_cpu_Pipeline_VITIS_LOOP_22_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start,
        ap_done => grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done,
        ap_idle => grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_idle,
        ap_ready => grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_ready,
        reg_file_address0 => grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_address0,
        reg_file_ce0 => grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_ce0,
        reg_file_we0 => grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_we0,
        reg_file_d0 => grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_d0);

    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38 : component cpu_cpu_Pipeline_PROGRAM_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start,
        ap_done => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done,
        ap_idle => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_idle,
        ap_ready => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_ready,
        mem_address0 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_address0,
        mem_ce0 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_ce0,
        mem_we0 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_we0,
        mem_d0 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_d0,
        mem_q0 => mem_q0,
        reg_file_address0 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address0,
        reg_file_ce0 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce0,
        reg_file_we0 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_we0,
        reg_file_d0 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_d0,
        reg_file_q0 => reg_file_q0,
        reg_file_address1 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address1,
        reg_file_ce1 => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce1,
        reg_file_q1 => reg_file_q1,
        pstrb => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb,
        pstrb_ap_vld => grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_ready = ap_const_logic_1)) then 
                    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_ready = ap_const_logic_1)) then 
                    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                pstrb_reg <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done, grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done)
    begin
        if ((grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done)
    begin
        if ((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg;
    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start <= grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg;
    mem_address0 <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_address0;
    mem_ce0 <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_ce0;
    mem_d0 <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_d0;
    mem_we0 <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_we0;

    pstrb_assign_proc : process(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb, grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb_ap_vld, ap_CS_fsm_state4, pstrb_reg)
    begin
        if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            pstrb <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb;
        else 
            pstrb <= pstrb_reg;
        end if; 
    end process;


    reg_file_address0_assign_proc : process(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_address0, grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_address0 <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            reg_file_address0 <= grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_address0;
        else 
            reg_file_address0 <= "XXXXX";
        end if; 
    end process;


    reg_file_ce0_assign_proc : process(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_ce0, grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_ce0 <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            reg_file_ce0 <= grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_ce0;
        else 
            reg_file_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_ce1_assign_proc : process(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_ce1 <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce1;
        else 
            reg_file_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_d0_assign_proc : process(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_d0, grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_d0 <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            reg_file_d0 <= grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_d0;
        else 
            reg_file_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    reg_file_we0_assign_proc : process(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_we0, grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_we0 <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            reg_file_we0 <= grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_we0;
        else 
            reg_file_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
