[hls]
relative_roots=C:/Users/aa099259/GitHub_personal/hls_riscv_ELEC5803/hls_riscv_csim_phase1
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=cpu/VITIS_LOOP_22_1 
syn.directive.pipeline=cpu/PROGRAM_LOOP 


