// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cpu_cpu_Pipeline_PROGRAM_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mem_address0,
        mem_ce0,
        mem_we0,
        mem_d0,
        mem_q0,
        reg_file_address0,
        reg_file_ce0,
        reg_file_we0,
        reg_file_d0,
        reg_file_q0,
        reg_file_address1,
        reg_file_ce1,
        reg_file_q1,
        pstrb,
        pstrb_ap_vld
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] mem_address0;
output   mem_ce0;
output   mem_we0;
output  [31:0] mem_d0;
input  [31:0] mem_q0;
output  [4:0] reg_file_address0;
output   reg_file_ce0;
output   reg_file_we0;
output  [31:0] reg_file_d0;
input  [31:0] reg_file_q0;
output  [4:0] reg_file_address1;
output   reg_file_ce1;
input  [31:0] reg_file_q1;
output  [3:0] pstrb;
output   pstrb_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] pstrb;
reg pstrb_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] pc_1_reg_1149;
wire    ap_CS_fsm_state2;
wire   [6:0] opcode_fu_468_p1;
reg   [6:0] opcode_reg_1163;
wire    ap_CS_fsm_state3;
reg   [4:0] rd_reg_1172;
wire   [2:0] func3_fu_496_p3;
reg   [2:0] func3_reg_1178;
wire   [9:0] funcx_fu_526_p3;
reg   [9:0] funcx_reg_1185;
wire  signed [31:0] sext_ln53_fu_544_p1;
wire  signed [31:0] sext_ln55_fu_592_p1;
wire  signed [31:0] sext_ln57_fu_628_p1;
wire   [31:0] imm_3_fu_656_p17;
wire   [31:0] imm_4_fu_700_p3;
wire   [0:0] icmp_ln95_fu_757_p2;
reg   [0:0] icmp_ln95_reg_1220;
reg   [31:0] src1_reg_1229;
wire    ap_CS_fsm_state4;
wire   [31:0] addr_fu_768_p2;
reg   [31:0] addr_reg_1251;
wire    ap_CS_fsm_state5;
wire   [1:0] trunc_ln99_fu_773_p1;
reg   [1:0] trunc_ln99_reg_1257;
wire   [31:0] res_b_fu_777_p2;
wire   [31:0] pc_2_fu_782_p2;
reg   [31:0] pc_2_reg_1267;
wire   [31:0] imm12_fu_787_p2;
wire   [31:0] res_j_8_fu_835_p3;
wire   [31:0] res_j_7_fu_843_p3;
wire   [31:0] res_j_6_fu_857_p3;
wire   [31:0] res_j_5_fu_865_p3;
wire   [31:0] res_j_4_fu_878_p3;
wire   [31:0] res_j_3_fu_891_p3;
wire   [0:0] icmp_ln155_fu_908_p2;
reg   [0:0] icmp_ln155_reg_1309;
wire   [31:0] zext_ln149_fu_965_p1;
wire   [31:0] zext_ln146_fu_969_p1;
wire   [31:0] res_10_fu_973_p2;
reg   [31:0] res_10_reg_1328;
wire   [31:0] res_9_fu_978_p2;
reg   [31:0] res_9_reg_1333;
wire   [31:0] res_8_fu_983_p2;
reg   [31:0] res_8_reg_1338;
wire   [31:0] res_7_fu_988_p2;
wire   [31:0] res_6_fu_993_p2;
wire   [31:0] res_5_fu_998_p2;
wire   [31:0] res_4_fu_1003_p2;
wire   [31:0] res_3_fu_1008_p2;
wire   [31:0] res_fu_1013_p2;
reg   [31:0] imm_5_reg_242;
reg   [31:0] src2_reg_262;
reg   [31:0] ap_phi_mux_res_2_phi_fu_277_p58;
reg   [31:0] res_2_reg_273;
reg    ap_predicate_pred216_state5;
reg    ap_predicate_pred220_state5;
reg    ap_predicate_pred224_state5;
reg    ap_predicate_pred236_state5;
reg    ap_predicate_pred244_state5;
wire    ap_CS_fsm_state6;
reg    ap_predicate_pred257_state6;
reg    ap_predicate_pred265_state6;
reg    ap_predicate_pred273_state6;
reg    ap_predicate_pred281_state5;
reg    ap_predicate_pred289_state5;
reg    ap_predicate_pred297_state5;
reg    ap_predicate_pred305_state5;
reg    ap_predicate_pred313_state5;
reg    ap_predicate_pred317_state5;
reg    ap_predicate_pred351_state5;
reg    ap_predicate_pred385_state5;
reg    ap_predicate_pred392_state5;
reg    ap_predicate_pred399_state5;
reg    ap_predicate_pred404_state5;
reg    ap_predicate_pred409_state5;
reg    ap_predicate_pred414_state5;
reg    ap_predicate_pred419_state5;
wire   [31:0] zext_ln171_fu_1022_p1;
wire   [31:0] zext_ln168_fu_1031_p1;
wire  signed [31:0] sext_ln165_fu_1040_p1;
wire  signed [31:0] sext_ln162_fu_1049_p1;
reg    ap_predicate_pred445_state5;
reg   [31:0] ap_phi_mux_res_j_1_phi_fu_354_p58;
reg   [31:0] res_j_1_reg_350;
wire   [63:0] zext_ln34_fu_463_p1;
wire   [63:0] zext_ln94_fu_728_p1;
wire   [63:0] zext_ln95_fu_763_p1;
wire   [63:0] zext_ln159_fu_924_p1;
wire   [63:0] zext_ln248_fu_1075_p1;
wire   [0:0] icmp_ln244_fu_1061_p2;
wire   [63:0] zext_ln252_fu_1085_p1;
wire   [0:0] icmp_ln251_fu_1080_p2;
reg   [31:0] pc_fu_166;
wire   [31:0] select_ln256_fu_1129_p3;
wire   [0:0] or_ln13_1_fu_1110_p2;
wire   [0:0] icmp_ln256_fu_1123_p2;
reg    ap_predicate_pred567_state5;
reg    ap_predicate_pred572_state5;
reg    ap_predicate_pred577_state5;
reg    mem_ce0_local;
reg   [9:0] mem_address0_local;
reg    mem_we0_local;
reg    reg_file_ce1_local;
reg    reg_file_ce0_local;
reg   [4:0] reg_file_address0_local;
reg    reg_file_we0_local;
wire   [9:0] lshr_ln_fu_453_p4;
wire   [0:0] icmp_ln47_fu_512_p2;
wire   [6:0] func7_fu_504_p3;
wire   [6:0] func7_1_fu_518_p3;
wire   [11:0] immI_fu_534_p4;
wire   [6:0] tmp_2_fu_564_p4;
wire   [4:0] tmp_3_fu_574_p4;
wire   [11:0] immS_fu_584_p3;
wire   [0:0] tmp_4_fu_606_p3;
wire   [0:0] tmp_fu_548_p3;
wire   [5:0] tmp_5_fu_596_p4;
wire   [3:0] tmp_1_fu_556_p3;
wire   [12:0] imm_2_fu_614_p6;
wire   [7:0] tmp_9_fu_648_p3;
wire   [0:0] tmp_6_fu_640_p3;
wire   [9:0] tmp_s_fu_632_p3;
wire   [19:0] tmp_7_fu_692_p3;
wire   [4:0] rs1_fu_480_p3;
wire   [1:0] tmp_8_fu_733_p4;
wire   [3:0] trunc_ln95_fu_743_p1;
wire   [6:0] or_ln_fu_747_p4;
wire   [4:0] rs2_fu_488_p3;
wire   [0:0] grp_fu_435_p2;
wire   [0:0] xor_ln213_fu_829_p2;
wire   [0:0] grp_fu_440_p2;
wire   [0:0] xor_ln207_fu_851_p2;
wire   [0:0] icmp_ln201_fu_873_p2;
wire   [0:0] icmp_ln198_fu_886_p2;
wire   [9:0] lshr_ln1_fu_914_p4;
wire   [15:0] res_16_fu_1018_p1;
wire   [7:0] res_15_fu_1027_p1;
wire   [15:0] res_14_fu_1036_p1;
wire   [7:0] res_13_fu_1045_p1;
wire   [9:0] lshr_ln2_fu_1066_p4;
wire   [0:0] icmp_ln13_1_fu_1094_p2;
wire   [0:0] icmp_ln13_fu_1089_p2;
wire   [0:0] icmp_ln13_2_fu_1105_p2;
wire   [0:0] or_ln13_fu_1099_p2;
wire   [1:0] trunc_ln256_fu_1120_p1;
reg    ap_predicate_pred355_state5;
reg    ap_predicate_pred445_state6;
wire    ap_CS_fsm_state7;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_condition_427;
reg    ap_condition_431;
reg    ap_condition_435;
reg    ap_condition_439;
reg    ap_condition_443;
reg    ap_condition_199;
reg    ap_condition_204;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 pc_fu_166 = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((1'b1 == ap_condition_204)) begin
            imm_5_reg_242 <= sext_ln53_fu_544_p1;
        end else if (((opcode_fu_468_p1 == 7'd23) | (opcode_fu_468_p1 == 7'd55))) begin
            imm_5_reg_242 <= imm_4_fu_700_p3;
        end else if ((1'b1 == ap_condition_199)) begin
            imm_5_reg_242 <= 32'd0;
        end else if ((opcode_fu_468_p1 == 7'd35)) begin
            imm_5_reg_242 <= sext_ln55_fu_592_p1;
        end else if ((opcode_fu_468_p1 == 7'd99)) begin
            imm_5_reg_242 <= sext_ln57_fu_628_p1;
        end else if ((opcode_fu_468_p1 == 7'd111)) begin
            imm_5_reg_242 <= imm_3_fu_656_p17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        pc_fu_166 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & ((((((((((opcode_reg_1163 == 7'd51) & (icmp_ln256_fu_1123_p2 == 1'd0) & (or_ln13_1_fu_1110_p2 == 1'd1)) | ((opcode_reg_1163 == 7'd23) & (icmp_ln256_fu_1123_p2 == 1'd0) & (or_ln13_1_fu_1110_p2 == 1'd1))) | ((opcode_reg_1163 == 7'd55) & (icmp_ln256_fu_1123_p2 == 1'd0) & (or_ln13_1_fu_1110_p2 == 1'd1))) | ((opcode_reg_1163 == 7'd111) & (icmp_ln256_fu_1123_p2 == 1'd0) & (or_ln13_1_fu_1110_p2 == 1'd1))) | ((opcode_reg_1163 == 7'd99) & (icmp_ln256_fu_1123_p2 == 1'd0) & (or_ln13_1_fu_1110_p2 == 1'd1))) | ((opcode_reg_1163 == 7'd35) & (icmp_ln256_fu_1123_p2 == 1'd0) & (or_ln13_1_fu_1110_p2 == 1'd1))) | ((opcode_reg_1163 == 7'd103) & (icmp_ln256_fu_1123_p2 == 1'd0) & (or_ln13_1_fu_1110_p2 == 1'd1))) | ((opcode_reg_1163 == 7'd3) & (icmp_ln256_fu_1123_p2 == 1'd0) & (or_ln13_1_fu_1110_p2 == 1'd1) & (icmp_ln155_reg_1309 == 1'd1))) | ((opcode_reg_1163 == 7'd19) & (icmp_ln256_fu_1123_p2 == 1'd0) & (or_ln13_1_fu_1110_p2 == 1'd1))))) begin
        pc_fu_166 <= select_ln256_fu_1129_p3;
    end else if (((1'b1 == ap_CS_fsm_state6) & ((((((((((opcode_reg_1163 == 7'd51) & (or_ln13_1_fu_1110_p2 == 1'd0)) | ((opcode_reg_1163 == 7'd23) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd55) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd111) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd99) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd35) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd103) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd3) & (or_ln13_1_fu_1110_p2 == 1'd0) & (icmp_ln155_reg_1309 == 1'd1))) | ((opcode_reg_1163 == 7'd19) & (or_ln13_1_fu_1110_p2 == 1'd0))))) begin
        pc_fu_166 <= pc_2_reg_1267;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred445_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= src2_reg_262;
    end else if (((func3_reg_1178 == 3'd0) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1))) begin
        res_2_reg_273 <= sext_ln162_fu_1049_p1;
    end else if (((func3_reg_1178 == 3'd1) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1))) begin
        res_2_reg_273 <= sext_ln165_fu_1040_p1;
    end else if (((func3_reg_1178 == 3'd4) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1))) begin
        res_2_reg_273 <= zext_ln168_fu_1031_p1;
    end else if (((func3_reg_1178 == 3'd5) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1))) begin
        res_2_reg_273 <= zext_ln171_fu_1022_p1;
    end else if (((func3_reg_1178 == 3'd2) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1))) begin
        res_2_reg_273 <= mem_q0;
    end else if ((((ap_predicate_pred419_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred414_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred409_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred404_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred399_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred392_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred385_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | (~(func3_reg_1178 == 3'd2) & ~(func3_reg_1178 == 3'd5) & ~(func3_reg_1178 == 3'd4) & ~(func3_reg_1178 == 3'd1) & ~(func3_reg_1178 == 3'd0) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln155_fu_908_p2 == 1'd1)) | ((ap_predicate_pred351_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        res_2_reg_273 <= 32'd0;
    end else if (((ap_predicate_pred317_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= imm12_fu_787_p2;
    end else if (((ap_predicate_pred313_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= res_3_fu_1008_p2;
    end else if (((ap_predicate_pred305_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= res_4_fu_1003_p2;
    end else if (((ap_predicate_pred297_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= res_5_fu_998_p2;
    end else if (((ap_predicate_pred289_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= res_6_fu_993_p2;
    end else if (((ap_predicate_pred281_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= res_7_fu_988_p2;
    end else if (((ap_predicate_pred273_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_2_reg_273 <= res_8_reg_1338;
    end else if (((ap_predicate_pred265_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_2_reg_273 <= res_9_reg_1333;
    end else if (((ap_predicate_pred257_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_2_reg_273 <= res_10_reg_1328;
    end else if (((ap_predicate_pred244_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= zext_ln146_fu_969_p1;
    end else if (((ap_predicate_pred236_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= zext_ln149_fu_965_p1;
    end else if ((((ap_predicate_pred224_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred220_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        res_2_reg_273 <= pc_2_fu_782_p2;
    end else if (((ap_predicate_pred216_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_2_reg_273 <= res_fu_1013_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred419_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_j_1_reg_350 <= res_j_3_fu_891_p3;
    end else if (((ap_predicate_pred414_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_j_1_reg_350 <= res_j_4_fu_878_p3;
    end else if (((ap_predicate_pred409_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_j_1_reg_350 <= res_j_5_fu_865_p3;
    end else if (((ap_predicate_pred404_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_j_1_reg_350 <= res_j_6_fu_857_p3;
    end else if (((ap_predicate_pred399_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_j_1_reg_350 <= res_j_7_fu_843_p3;
    end else if (((ap_predicate_pred392_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_j_1_reg_350 <= res_j_8_fu_835_p3;
    end else if (((ap_predicate_pred224_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_j_1_reg_350 <= res_b_fu_777_p2;
    end else if (((ap_predicate_pred220_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        res_j_1_reg_350 <= addr_fu_768_p2;
    end else if ((((ap_predicate_pred445_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred385_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | (~(func3_reg_1178 == 3'd2) & ~(func3_reg_1178 == 3'd5) & ~(func3_reg_1178 == 3'd4) & ~(func3_reg_1178 == 3'd1) & ~(func3_reg_1178 == 3'd0) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln155_fu_908_p2 == 1'd1)) | ((func3_reg_1178 == 3'd2) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((func3_reg_1178 == 3'd5) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((func3_reg_1178 == 3'd4) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((func3_reg_1178 == 3'd1) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((func3_reg_1178 == 3'd0) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((ap_predicate_pred351_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) 
    | ((ap_predicate_pred317_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred313_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred305_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred297_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred289_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred281_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred273_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((ap_predicate_pred265_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((ap_predicate_pred257_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((ap_predicate_pred244_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred236_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred216_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        res_j_1_reg_350 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((icmp_ln95_reg_1220 == 1'd0)) begin
            src2_reg_262 <= imm_5_reg_242;
        end else if ((icmp_ln95_reg_1220 == 1'd1)) begin
            src2_reg_262 <= reg_file_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        addr_reg_1251 <= addr_fu_768_p2;
        ap_predicate_pred257_state6 <= (((funcx_reg_1185 == 10'd261) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd261) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred265_state6 <= (((funcx_reg_1185 == 10'd5) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd5) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred273_state6 <= (((funcx_reg_1185 == 10'd1) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd1) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred445_state6 <= (opcode_reg_1163 == 7'd35);
        icmp_ln155_reg_1309 <= icmp_ln155_fu_908_p2;
        pc_2_reg_1267 <= pc_2_fu_782_p2;
        res_10_reg_1328 <= res_10_fu_973_p2;
        res_8_reg_1338 <= res_8_fu_983_p2;
        res_9_reg_1333 <= res_9_fu_978_p2;
        trunc_ln99_reg_1257 <= trunc_ln99_fu_773_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_predicate_pred216_state5 <= (opcode_reg_1163 == 7'd23);
        ap_predicate_pred220_state5 <= (opcode_reg_1163 == 7'd103);
        ap_predicate_pred224_state5 <= (opcode_reg_1163 == 7'd111);
        ap_predicate_pred236_state5 <= (((funcx_reg_1185 == 10'd3) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd3) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred244_state5 <= (((funcx_reg_1185 == 10'd2) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd2) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred281_state5 <= (((funcx_reg_1185 == 10'd112) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd112) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred289_state5 <= (((funcx_reg_1185 == 10'd96) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd96) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred297_state5 <= (((funcx_reg_1185 == 10'd64) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd64) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred305_state5 <= (((funcx_reg_1185 == 10'd256) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd256) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred313_state5 <= (((funcx_reg_1185 == 10'd0) & (opcode_reg_1163 == 7'd19)) | ((funcx_reg_1185 == 10'd0) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred317_state5 <= (opcode_reg_1163 == 7'd55);
        ap_predicate_pred351_state5 <= ((~(funcx_reg_1185 == 10'd0) & ~(funcx_reg_1185 == 10'd256) & ~(funcx_reg_1185 == 10'd64) & ~(funcx_reg_1185 == 10'd96) & ~(funcx_reg_1185 == 10'd112) & ~(funcx_reg_1185 == 10'd1) & ~(funcx_reg_1185 == 10'd5) & ~(funcx_reg_1185 == 10'd261) & ~(funcx_reg_1185 == 10'd2) & ~(funcx_reg_1185 == 10'd3) & (opcode_reg_1163 == 7'd19)) | (~(funcx_reg_1185 == 10'd0) & ~(funcx_reg_1185 == 10'd256) & ~(funcx_reg_1185 == 10'd64) & ~(funcx_reg_1185 == 10'd96) & ~(funcx_reg_1185 == 10'd112) & ~(funcx_reg_1185 == 10'd1) & ~(funcx_reg_1185 == 10'd5) & ~(funcx_reg_1185 == 10'd261) & ~(funcx_reg_1185 == 10'd2) & ~(funcx_reg_1185 == 10'd3) & (opcode_reg_1163 == 7'd51)));
        ap_predicate_pred355_state5 <= (opcode_reg_1163 == 7'd3);
        ap_predicate_pred385_state5 <= (((func3_reg_1178 == 3'd3) & (opcode_reg_1163 == 7'd99)) | ((func3_reg_1178 == 3'd2) & (opcode_reg_1163 == 7'd99)));
        ap_predicate_pred392_state5 <= ((func3_reg_1178 == 3'd7) & (opcode_reg_1163 == 7'd99));
        ap_predicate_pred399_state5 <= ((func3_reg_1178 == 3'd6) & (opcode_reg_1163 == 7'd99));
        ap_predicate_pred404_state5 <= ((func3_reg_1178 == 3'd5) & (opcode_reg_1163 == 7'd99));
        ap_predicate_pred409_state5 <= ((func3_reg_1178 == 3'd4) & (opcode_reg_1163 == 7'd99));
        ap_predicate_pred414_state5 <= ((func3_reg_1178 == 3'd1) & (opcode_reg_1163 == 7'd99));
        ap_predicate_pred419_state5 <= ((func3_reg_1178 == 3'd0) & (opcode_reg_1163 == 7'd99));
        ap_predicate_pred445_state5 <= (opcode_reg_1163 == 7'd35);
        ap_predicate_pred567_state5 <= ((func3_reg_1178 == 3'd2) & (opcode_reg_1163 == 7'd35));
        ap_predicate_pred572_state5 <= ((func3_reg_1178 == 3'd1) & (opcode_reg_1163 == 7'd35));
        ap_predicate_pred577_state5 <= ((func3_reg_1178 == 3'd0) & (opcode_reg_1163 == 7'd35));
        src1_reg_1229 <= reg_file_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        func3_reg_1178 <= {{mem_q0[14:12]}};
        funcx_reg_1185 <= funcx_fu_526_p3;
        icmp_ln95_reg_1220 <= icmp_ln95_fu_757_p2;
        opcode_reg_1163 <= opcode_fu_468_p1;
        rd_reg_1172 <= {{mem_q0[11:7]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        pc_1_reg_1149 <= pc_fu_166;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((1'b1 == ap_condition_443)) begin
            ap_phi_mux_res_2_phi_fu_277_p58 = sext_ln162_fu_1049_p1;
        end else if ((1'b1 == ap_condition_439)) begin
            ap_phi_mux_res_2_phi_fu_277_p58 = sext_ln165_fu_1040_p1;
        end else if ((1'b1 == ap_condition_435)) begin
            ap_phi_mux_res_2_phi_fu_277_p58 = zext_ln168_fu_1031_p1;
        end else if ((1'b1 == ap_condition_431)) begin
            ap_phi_mux_res_2_phi_fu_277_p58 = zext_ln171_fu_1022_p1;
        end else if ((1'b1 == ap_condition_427)) begin
            ap_phi_mux_res_2_phi_fu_277_p58 = mem_q0;
        end else if ((ap_predicate_pred273_state6 == 1'b1)) begin
            ap_phi_mux_res_2_phi_fu_277_p58 = res_8_reg_1338;
        end else if ((ap_predicate_pred265_state6 == 1'b1)) begin
            ap_phi_mux_res_2_phi_fu_277_p58 = res_9_reg_1333;
        end else if ((ap_predicate_pred257_state6 == 1'b1)) begin
            ap_phi_mux_res_2_phi_fu_277_p58 = res_10_reg_1328;
        end else begin
            ap_phi_mux_res_2_phi_fu_277_p58 = res_2_reg_273;
        end
    end else begin
        ap_phi_mux_res_2_phi_fu_277_p58 = res_2_reg_273;
    end
end

always @ (*) begin
    if ((((func3_reg_1178 == 3'd2) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((func3_reg_1178 == 3'd5) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((func3_reg_1178 == 3'd4) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((func3_reg_1178 == 3'd1) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((func3_reg_1178 == 3'd0) & (opcode_reg_1163 == 7'd3) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln155_reg_1309 == 1'd1)) | ((ap_predicate_pred273_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((ap_predicate_pred265_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((ap_predicate_pred257_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        ap_phi_mux_res_j_1_phi_fu_354_p58 = 32'd0;
    end else begin
        ap_phi_mux_res_j_1_phi_fu_354_p58 = res_j_1_reg_350;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mem_address0_local = zext_ln248_fu_1075_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mem_address0_local = zext_ln159_fu_924_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mem_address0_local = zext_ln34_fu_463_p1;
    end else begin
        mem_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        mem_ce0_local = 1'b1;
    end else begin
        mem_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((opcode_reg_1163 == 7'd35) & (icmp_ln244_fu_1061_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        mem_we0_local = 1'b1;
    end else begin
        mem_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((ap_predicate_pred577_state5 == 1'b1)) begin
            pstrb = 4'd1;
        end else if ((ap_predicate_pred572_state5 == 1'b1)) begin
            pstrb = 4'd3;
        end else if ((ap_predicate_pred567_state5 == 1'b1)) begin
            pstrb = 4'd15;
        end else begin
            pstrb = 'bx;
        end
    end else begin
        pstrb = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred577_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred572_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_predicate_pred567_state5 == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        pstrb_ap_vld = 1'b1;
    end else begin
        pstrb_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_address0_local = zext_ln252_fu_1085_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        reg_file_address0_local = zext_ln95_fu_763_p1;
    end else begin
        reg_file_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state6))) begin
        reg_file_ce0_local = 1'b1;
    end else begin
        reg_file_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        reg_file_ce1_local = 1'b1;
    end else begin
        reg_file_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & ((((((((opcode_reg_1163 == 7'd51) & (icmp_ln251_fu_1080_p2 == 1'd0)) | ((opcode_reg_1163 == 7'd23) & (icmp_ln251_fu_1080_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd55) & (icmp_ln251_fu_1080_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd111) & (icmp_ln251_fu_1080_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd103) & (icmp_ln251_fu_1080_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd3) & (icmp_ln251_fu_1080_p2 == 1'd0) & (icmp_ln155_reg_1309 == 1'd1))) | ((opcode_reg_1163 == 7'd19) & (icmp_ln251_fu_1080_p2 == 1'd0))))) begin
        reg_file_we0_local = 1'b1;
    end else begin
        reg_file_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (((((((((((((((((((opcode_reg_1163 == 7'd51) & (icmp_ln256_fu_1123_p2 == 1'd0)) | ((opcode_reg_1163 == 7'd51) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd23) & (icmp_ln256_fu_1123_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd23) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd55) & (icmp_ln256_fu_1123_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd55) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd111) & (icmp_ln256_fu_1123_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd111) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd99) & (icmp_ln256_fu_1123_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd99) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd35) & (icmp_ln256_fu_1123_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd35) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd103) & (icmp_ln256_fu_1123_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd103) & (or_ln13_1_fu_1110_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd3) & (icmp_ln256_fu_1123_p2 == 1'd0) 
    & (icmp_ln155_reg_1309 == 1'd1))) | ((opcode_reg_1163 == 7'd3) & (or_ln13_1_fu_1110_p2 == 1'd0) & (icmp_ln155_reg_1309 == 1'd1))) | ((opcode_reg_1163 == 7'd19) & (icmp_ln256_fu_1123_p2 == 1'd0))) | ((opcode_reg_1163 == 7'd19) & (or_ln13_1_fu_1110_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state6) & (((opcode_reg_1163 == 7'd3) & (icmp_ln155_reg_1309 == 1'd0)) | (~(opcode_reg_1163 == 7'd35) & ~(opcode_reg_1163 == 7'd99) & ~(opcode_reg_1163 == 7'd3) & ~(opcode_reg_1163 == 7'd55) & ~(opcode_reg_1163 == 7'd19) & ~(opcode_reg_1163 == 7'd51) & ~(opcode_reg_1163 == 7'd111) & ~(opcode_reg_1163 == 7'd103) & ~(opcode_reg_1163 == 7'd23))))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign addr_fu_768_p2 = (src1_reg_1229 + imm_5_reg_242);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_condition_199 = (~(opcode_fu_468_p1 == 7'd23) & ~(opcode_fu_468_p1 == 7'd55) & ~(opcode_fu_468_p1 == 7'd103) & ~(opcode_fu_468_p1 == 7'd3) & ~(opcode_fu_468_p1 == 7'd19) & ~(opcode_fu_468_p1 == 7'd35) & ~(opcode_fu_468_p1 == 7'd99) & ~(opcode_fu_468_p1 == 7'd111));
end

always @ (*) begin
    ap_condition_204 = ((opcode_fu_468_p1 == 7'd19) | ((opcode_fu_468_p1 == 7'd103) | (opcode_fu_468_p1 == 7'd3)));
end

always @ (*) begin
    ap_condition_427 = ((func3_reg_1178 == 3'd2) & (opcode_reg_1163 == 7'd3) & (icmp_ln155_reg_1309 == 1'd1));
end

always @ (*) begin
    ap_condition_431 = ((func3_reg_1178 == 3'd5) & (opcode_reg_1163 == 7'd3) & (icmp_ln155_reg_1309 == 1'd1));
end

always @ (*) begin
    ap_condition_435 = ((func3_reg_1178 == 3'd4) & (opcode_reg_1163 == 7'd3) & (icmp_ln155_reg_1309 == 1'd1));
end

always @ (*) begin
    ap_condition_439 = ((func3_reg_1178 == 3'd1) & (opcode_reg_1163 == 7'd3) & (icmp_ln155_reg_1309 == 1'd1));
end

always @ (*) begin
    ap_condition_443 = ((func3_reg_1178 == 3'd0) & (opcode_reg_1163 == 7'd3) & (icmp_ln155_reg_1309 == 1'd1));
end

assign func3_fu_496_p3 = {{mem_q0[14:12]}};

assign func7_1_fu_518_p3 = ((icmp_ln47_fu_512_p2[0:0] == 1'b1) ? func7_fu_504_p3 : 7'd0);

assign func7_fu_504_p3 = {{mem_q0[31:25]}};

assign funcx_fu_526_p3 = {{func7_1_fu_518_p3}, {func3_fu_496_p3}};

assign grp_fu_435_p2 = ((src1_reg_1229 < src2_reg_262) ? 1'b1 : 1'b0);

assign grp_fu_440_p2 = (($signed(src1_reg_1229) < $signed(src2_reg_262)) ? 1'b1 : 1'b0);

assign icmp_ln13_1_fu_1094_p2 = ((opcode_reg_1163 == 7'd103) ? 1'b1 : 1'b0);

assign icmp_ln13_2_fu_1105_p2 = ((opcode_reg_1163 == 7'd99) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_1089_p2 = ((opcode_reg_1163 == 7'd111) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_908_p2 = ((trunc_ln99_fu_773_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln198_fu_886_p2 = ((src1_reg_1229 == src2_reg_262) ? 1'b1 : 1'b0);

assign icmp_ln201_fu_873_p2 = ((src1_reg_1229 != src2_reg_262) ? 1'b1 : 1'b0);

assign icmp_ln244_fu_1061_p2 = ((trunc_ln99_reg_1257 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln251_fu_1080_p2 = ((rd_reg_1172 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln256_fu_1123_p2 = ((trunc_ln256_fu_1120_p1 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_512_p2 = ((opcode_fu_468_p1 == 7'd51) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_757_p2 = ((or_ln_fu_747_p4 == 7'd51) ? 1'b1 : 1'b0);

assign imm12_fu_787_p2 = imm_5_reg_242 << 32'd12;

assign immI_fu_534_p4 = {{mem_q0[31:20]}};

assign immS_fu_584_p3 = {{tmp_2_fu_564_p4}, {tmp_3_fu_574_p4}};

assign imm_2_fu_614_p6 = {{{{{tmp_4_fu_606_p3}, {tmp_fu_548_p3}}, {tmp_5_fu_596_p4}}, {tmp_1_fu_556_p3}}, {1'd0}};

assign imm_3_fu_656_p17 = {{{{{{{{{{{{{{{{tmp_4_fu_606_p3}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_4_fu_606_p3}}, {tmp_9_fu_648_p3}}, {tmp_6_fu_640_p3}}, {tmp_s_fu_632_p3}}, {1'd0}};

assign imm_4_fu_700_p3 = {{tmp_7_fu_692_p3}, {12'd0}};

assign lshr_ln1_fu_914_p4 = {{addr_fu_768_p2[11:2]}};

assign lshr_ln2_fu_1066_p4 = {{addr_reg_1251[11:2]}};

assign lshr_ln_fu_453_p4 = {{pc_fu_166[11:2]}};

assign mem_address0 = mem_address0_local;

assign mem_ce0 = mem_ce0_local;

assign mem_d0 = ap_phi_mux_res_2_phi_fu_277_p58;

assign mem_we0 = mem_we0_local;

assign opcode_fu_468_p1 = mem_q0[6:0];

assign or_ln13_1_fu_1110_p2 = (or_ln13_fu_1099_p2 | icmp_ln13_2_fu_1105_p2);

assign or_ln13_fu_1099_p2 = (icmp_ln13_fu_1089_p2 | icmp_ln13_1_fu_1094_p2);

assign or_ln_fu_747_p4 = {{{tmp_8_fu_733_p4}, {1'd1}}, {trunc_ln95_fu_743_p1}};

assign pc_2_fu_782_p2 = (pc_1_reg_1149 + 32'd4);

assign reg_file_address0 = reg_file_address0_local;

assign reg_file_address1 = zext_ln94_fu_728_p1;

assign reg_file_ce0 = reg_file_ce0_local;

assign reg_file_ce1 = reg_file_ce1_local;

assign reg_file_d0 = ap_phi_mux_res_2_phi_fu_277_p58;

assign reg_file_we0 = reg_file_we0_local;

assign res_10_fu_973_p2 = $signed(src1_reg_1229) >>> src2_reg_262;

assign res_13_fu_1045_p1 = mem_q0[7:0];

assign res_14_fu_1036_p1 = mem_q0[15:0];

assign res_15_fu_1027_p1 = mem_q0[7:0];

assign res_16_fu_1018_p1 = mem_q0[15:0];

assign res_3_fu_1008_p2 = (src1_reg_1229 + src2_reg_262);

assign res_4_fu_1003_p2 = (src1_reg_1229 - src2_reg_262);

assign res_5_fu_998_p2 = (src2_reg_262 ^ src1_reg_1229);

assign res_6_fu_993_p2 = (src2_reg_262 | src1_reg_1229);

assign res_7_fu_988_p2 = (src2_reg_262 & src1_reg_1229);

assign res_8_fu_983_p2 = src1_reg_1229 << src2_reg_262;

assign res_9_fu_978_p2 = src1_reg_1229 >> src2_reg_262;

assign res_b_fu_777_p2 = (imm_5_reg_242 + pc_1_reg_1149);

assign res_fu_1013_p2 = (imm12_fu_787_p2 + pc_1_reg_1149);

assign res_j_3_fu_891_p3 = ((icmp_ln198_fu_886_p2[0:0] == 1'b1) ? res_b_fu_777_p2 : pc_2_fu_782_p2);

assign res_j_4_fu_878_p3 = ((icmp_ln201_fu_873_p2[0:0] == 1'b1) ? res_b_fu_777_p2 : pc_2_fu_782_p2);

assign res_j_5_fu_865_p3 = ((grp_fu_440_p2[0:0] == 1'b1) ? res_b_fu_777_p2 : pc_2_fu_782_p2);

assign res_j_6_fu_857_p3 = ((xor_ln207_fu_851_p2[0:0] == 1'b1) ? res_b_fu_777_p2 : pc_2_fu_782_p2);

assign res_j_7_fu_843_p3 = ((grp_fu_435_p2[0:0] == 1'b1) ? res_b_fu_777_p2 : pc_2_fu_782_p2);

assign res_j_8_fu_835_p3 = ((xor_ln213_fu_829_p2[0:0] == 1'b1) ? res_b_fu_777_p2 : pc_2_fu_782_p2);

assign rs1_fu_480_p3 = {{mem_q0[19:15]}};

assign rs2_fu_488_p3 = {{mem_q0[24:20]}};

assign select_ln256_fu_1129_p3 = ((icmp_ln256_fu_1123_p2[0:0] == 1'b1) ? pc_1_reg_1149 : ap_phi_mux_res_j_1_phi_fu_354_p58);

assign sext_ln162_fu_1049_p1 = $signed(res_13_fu_1045_p1);

assign sext_ln165_fu_1040_p1 = $signed(res_14_fu_1036_p1);

assign sext_ln53_fu_544_p1 = $signed(immI_fu_534_p4);

assign sext_ln55_fu_592_p1 = $signed(immS_fu_584_p3);

assign sext_ln57_fu_628_p1 = $signed(imm_2_fu_614_p6);

assign tmp_1_fu_556_p3 = {{mem_q0[11:8]}};

assign tmp_2_fu_564_p4 = {{mem_q0[31:25]}};

assign tmp_3_fu_574_p4 = {{mem_q0[11:7]}};

assign tmp_4_fu_606_p3 = mem_q0[32'd31];

assign tmp_5_fu_596_p4 = {{mem_q0[30:25]}};

assign tmp_6_fu_640_p3 = mem_q0[32'd20];

assign tmp_7_fu_692_p3 = {{mem_q0[31:12]}};

assign tmp_8_fu_733_p4 = {{mem_q0[6:5]}};

assign tmp_9_fu_648_p3 = {{mem_q0[19:12]}};

assign tmp_fu_548_p3 = mem_q0[32'd7];

assign tmp_s_fu_632_p3 = {{mem_q0[30:21]}};

assign trunc_ln256_fu_1120_p1 = pc_1_reg_1149[1:0];

assign trunc_ln95_fu_743_p1 = mem_q0[3:0];

assign trunc_ln99_fu_773_p1 = addr_fu_768_p2[1:0];

assign xor_ln207_fu_851_p2 = (grp_fu_440_p2 ^ 1'd1);

assign xor_ln213_fu_829_p2 = (grp_fu_435_p2 ^ 1'd1);

assign zext_ln146_fu_969_p1 = grp_fu_440_p2;

assign zext_ln149_fu_965_p1 = grp_fu_435_p2;

assign zext_ln159_fu_924_p1 = lshr_ln1_fu_914_p4;

assign zext_ln168_fu_1031_p1 = res_15_fu_1027_p1;

assign zext_ln171_fu_1022_p1 = res_16_fu_1018_p1;

assign zext_ln248_fu_1075_p1 = lshr_ln2_fu_1066_p4;

assign zext_ln252_fu_1085_p1 = rd_reg_1172;

assign zext_ln34_fu_463_p1 = lshr_ln_fu_453_p4;

assign zext_ln94_fu_728_p1 = rs1_fu_480_p3;

assign zext_ln95_fu_763_p1 = rs2_fu_488_p3;

endmodule //cpu_cpu_Pipeline_PROGRAM_LOOP
