-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cpu_cpu_Pipeline_PROGRAM_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mem_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    mem_ce0 : OUT STD_LOGIC;
    mem_we0 : OUT STD_LOGIC;
    mem_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mem_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    reg_file_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    reg_file_ce0 : OUT STD_LOGIC;
    reg_file_we0 : OUT STD_LOGIC;
    reg_file_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    reg_file_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    reg_file_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    reg_file_ce1 : OUT STD_LOGIC;
    reg_file_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    pstrb : OUT STD_LOGIC_VECTOR (3 downto 0);
    pstrb_ap_vld : OUT STD_LOGIC );
end;


architecture behav of cpu_cpu_Pipeline_PROGRAM_LOOP is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv7_6F : STD_LOGIC_VECTOR (6 downto 0) := "1101111";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv7_23 : STD_LOGIC_VECTOR (6 downto 0) := "0100011";
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv7_67 : STD_LOGIC_VECTOR (6 downto 0) := "1100111";
    constant ap_const_lv7_37 : STD_LOGIC_VECTOR (6 downto 0) := "0110111";
    constant ap_const_lv7_17 : STD_LOGIC_VECTOR (6 downto 0) := "0010111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_33 : STD_LOGIC_VECTOR (6 downto 0) := "0110011";
    constant ap_const_lv10_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000011";
    constant ap_const_lv10_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv10_105 : STD_LOGIC_VECTOR (9 downto 0) := "0100000101";
    constant ap_const_lv10_5 : STD_LOGIC_VECTOR (9 downto 0) := "0000000101";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_70 : STD_LOGIC_VECTOR (9 downto 0) := "0001110000";
    constant ap_const_lv10_60 : STD_LOGIC_VECTOR (9 downto 0) := "0001100000";
    constant ap_const_lv10_40 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_const_lv10_100 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal pc_1_reg_1149 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal opcode_fu_468_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal opcode_reg_1163 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal rd_reg_1172 : STD_LOGIC_VECTOR (4 downto 0);
    signal func3_fu_496_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal func3_reg_1178 : STD_LOGIC_VECTOR (2 downto 0);
    signal funcx_fu_526_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal funcx_reg_1185 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln53_fu_544_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln55_fu_592_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln57_fu_628_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal imm_3_fu_656_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal imm_4_fu_700_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln95_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln95_reg_1220 : STD_LOGIC_VECTOR (0 downto 0);
    signal src1_reg_1229 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal addr_fu_768_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal addr_reg_1251 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal trunc_ln99_fu_773_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln99_reg_1257 : STD_LOGIC_VECTOR (1 downto 0);
    signal res_b_fu_777_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal pc_2_fu_782_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal pc_2_reg_1267 : STD_LOGIC_VECTOR (31 downto 0);
    signal imm12_fu_787_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_j_8_fu_835_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_j_7_fu_843_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_j_6_fu_857_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_j_5_fu_865_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_j_4_fu_878_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_j_3_fu_891_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln155_fu_908_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln155_reg_1309 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln149_fu_965_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln146_fu_969_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_10_fu_973_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_10_reg_1328 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_9_fu_978_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_9_reg_1333 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_8_fu_983_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_8_reg_1338 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_7_fu_988_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_6_fu_993_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_5_fu_998_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_4_fu_1003_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_3_fu_1008_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_fu_1013_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal imm_5_reg_242 : STD_LOGIC_VECTOR (31 downto 0);
    signal src2_reg_262 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_res_2_phi_fu_277_p58 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_2_reg_273 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_pred216_state5 : BOOLEAN;
    signal ap_predicate_pred220_state5 : BOOLEAN;
    signal ap_predicate_pred224_state5 : BOOLEAN;
    signal ap_predicate_pred236_state5 : BOOLEAN;
    signal ap_predicate_pred244_state5 : BOOLEAN;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_predicate_pred257_state6 : BOOLEAN;
    signal ap_predicate_pred265_state6 : BOOLEAN;
    signal ap_predicate_pred273_state6 : BOOLEAN;
    signal ap_predicate_pred281_state5 : BOOLEAN;
    signal ap_predicate_pred289_state5 : BOOLEAN;
    signal ap_predicate_pred297_state5 : BOOLEAN;
    signal ap_predicate_pred305_state5 : BOOLEAN;
    signal ap_predicate_pred313_state5 : BOOLEAN;
    signal ap_predicate_pred317_state5 : BOOLEAN;
    signal ap_predicate_pred351_state5 : BOOLEAN;
    signal ap_predicate_pred385_state5 : BOOLEAN;
    signal ap_predicate_pred392_state5 : BOOLEAN;
    signal ap_predicate_pred399_state5 : BOOLEAN;
    signal ap_predicate_pred404_state5 : BOOLEAN;
    signal ap_predicate_pred409_state5 : BOOLEAN;
    signal ap_predicate_pred414_state5 : BOOLEAN;
    signal ap_predicate_pred419_state5 : BOOLEAN;
    signal zext_ln171_fu_1022_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln168_fu_1031_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln165_fu_1040_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln162_fu_1049_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_pred445_state5 : BOOLEAN;
    signal ap_phi_mux_res_j_1_phi_fu_354_p58 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_j_1_reg_350 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln34_fu_463_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln94_fu_728_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln95_fu_763_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln159_fu_924_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln248_fu_1075_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln244_fu_1061_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln252_fu_1085_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln251_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pc_fu_166 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln256_fu_1129_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln13_1_fu_1110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln256_fu_1123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_pred567_state5 : BOOLEAN;
    signal ap_predicate_pred572_state5 : BOOLEAN;
    signal ap_predicate_pred577_state5 : BOOLEAN;
    signal mem_ce0_local : STD_LOGIC;
    signal mem_address0_local : STD_LOGIC_VECTOR (9 downto 0);
    signal mem_we0_local : STD_LOGIC;
    signal reg_file_ce1_local : STD_LOGIC;
    signal reg_file_ce0_local : STD_LOGIC;
    signal reg_file_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal reg_file_we0_local : STD_LOGIC;
    signal lshr_ln_fu_453_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln47_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal func7_fu_504_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal func7_1_fu_518_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal immI_fu_534_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_fu_564_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_3_fu_574_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal immS_fu_584_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_4_fu_606_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_548_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_596_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_556_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal imm_2_fu_614_p6 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_9_fu_648_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_640_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_632_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_fu_692_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal rs1_fu_480_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_8_fu_733_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln95_fu_743_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln_fu_747_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal rs2_fu_488_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln213_fu_829_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln207_fu_851_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln201_fu_873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln198_fu_886_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln1_fu_914_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal res_16_fu_1018_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_15_fu_1027_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal res_14_fu_1036_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_13_fu_1045_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln2_fu_1066_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln13_1_fu_1094_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln13_fu_1089_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln13_2_fu_1105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln13_fu_1099_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln256_fu_1120_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_predicate_pred355_state5 : BOOLEAN;
    signal ap_predicate_pred445_state6 : BOOLEAN;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_condition_427 : BOOLEAN;
    signal ap_condition_431 : BOOLEAN;
    signal ap_condition_435 : BOOLEAN;
    signal ap_condition_439 : BOOLEAN;
    signal ap_condition_443 : BOOLEAN;
    signal ap_condition_199 : BOOLEAN;
    signal ap_condition_204 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    imm_5_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if ((ap_const_boolean_1 = ap_condition_204)) then 
                    imm_5_reg_242 <= sext_ln53_fu_544_p1;
                elsif (((opcode_fu_468_p1 = ap_const_lv7_17) or (opcode_fu_468_p1 = ap_const_lv7_37))) then 
                    imm_5_reg_242 <= imm_4_fu_700_p3;
                elsif ((ap_const_boolean_1 = ap_condition_199)) then 
                    imm_5_reg_242 <= ap_const_lv32_0;
                elsif ((opcode_fu_468_p1 = ap_const_lv7_23)) then 
                    imm_5_reg_242 <= sext_ln55_fu_592_p1;
                elsif ((opcode_fu_468_p1 = ap_const_lv7_63)) then 
                    imm_5_reg_242 <= sext_ln57_fu_628_p1;
                elsif ((opcode_fu_468_p1 = ap_const_lv7_6F)) then 
                    imm_5_reg_242 <= imm_3_fu_656_p17;
                end if;
            end if; 
        end if;
    end process;

    pc_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                pc_fu_166 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and ((((((((((opcode_reg_1163 = ap_const_lv7_33) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_1)) or ((opcode_reg_1163 = ap_const_lv7_17) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_37) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_6F) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_63) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_23) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_67) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_3) and (icmp_ln256_fu_1123_p2 
    = ap_const_lv1_0) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_1) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_13) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_1))))) then 
                pc_fu_166 <= select_ln256_fu_1129_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and ((((((((((opcode_reg_1163 = ap_const_lv7_33) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0)) or ((opcode_reg_1163 = ap_const_lv7_17) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_37) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_6F) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_63) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_23) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_67) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_3) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_13) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))))) then 
                pc_fu_166 <= pc_2_reg_1267;
            end if; 
        end if;
    end process;

    res_2_reg_273_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred445_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= src2_reg_262;
            elsif (((func3_reg_1178 = ap_const_lv3_0) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) then 
                res_2_reg_273 <= sext_ln162_fu_1049_p1;
            elsif (((func3_reg_1178 = ap_const_lv3_1) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) then 
                res_2_reg_273 <= sext_ln165_fu_1040_p1;
            elsif (((func3_reg_1178 = ap_const_lv3_4) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) then 
                res_2_reg_273 <= zext_ln168_fu_1031_p1;
            elsif (((func3_reg_1178 = ap_const_lv3_5) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) then 
                res_2_reg_273 <= zext_ln171_fu_1022_p1;
            elsif (((func3_reg_1178 = ap_const_lv3_2) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) then 
                res_2_reg_273 <= mem_q0;
            elsif ((((ap_predicate_pred419_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred414_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred409_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred404_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred399_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred392_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred385_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not((func3_reg_1178 = ap_const_lv3_2)) and not((func3_reg_1178 = ap_const_lv3_5)) and not((func3_reg_1178 = ap_const_lv3_4)) and not((func3_reg_1178 = ap_const_lv3_1)) and not((func3_reg_1178 = ap_const_lv3_0)) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln155_fu_908_p2 = ap_const_lv1_1)) 
    or ((ap_predicate_pred351_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
                res_2_reg_273 <= ap_const_lv32_0;
            elsif (((ap_predicate_pred317_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= imm12_fu_787_p2;
            elsif (((ap_predicate_pred313_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= res_3_fu_1008_p2;
            elsif (((ap_predicate_pred305_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= res_4_fu_1003_p2;
            elsif (((ap_predicate_pred297_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= res_5_fu_998_p2;
            elsif (((ap_predicate_pred289_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= res_6_fu_993_p2;
            elsif (((ap_predicate_pred281_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= res_7_fu_988_p2;
            elsif (((ap_predicate_pred273_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                res_2_reg_273 <= res_8_reg_1338;
            elsif (((ap_predicate_pred265_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                res_2_reg_273 <= res_9_reg_1333;
            elsif (((ap_predicate_pred257_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                res_2_reg_273 <= res_10_reg_1328;
            elsif (((ap_predicate_pred244_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= zext_ln146_fu_969_p1;
            elsif (((ap_predicate_pred236_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= zext_ln149_fu_965_p1;
            elsif ((((ap_predicate_pred224_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred220_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
                res_2_reg_273 <= pc_2_fu_782_p2;
            elsif (((ap_predicate_pred216_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_2_reg_273 <= res_fu_1013_p2;
            end if; 
        end if;
    end process;

    res_j_1_reg_350_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_pred419_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_j_1_reg_350 <= res_j_3_fu_891_p3;
            elsif (((ap_predicate_pred414_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_j_1_reg_350 <= res_j_4_fu_878_p3;
            elsif (((ap_predicate_pred409_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_j_1_reg_350 <= res_j_5_fu_865_p3;
            elsif (((ap_predicate_pred404_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_j_1_reg_350 <= res_j_6_fu_857_p3;
            elsif (((ap_predicate_pred399_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_j_1_reg_350 <= res_j_7_fu_843_p3;
            elsif (((ap_predicate_pred392_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_j_1_reg_350 <= res_j_8_fu_835_p3;
            elsif (((ap_predicate_pred224_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_j_1_reg_350 <= res_b_fu_777_p2;
            elsif (((ap_predicate_pred220_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                res_j_1_reg_350 <= addr_fu_768_p2;
            elsif ((((ap_predicate_pred445_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred385_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not((func3_reg_1178 = ap_const_lv3_2)) and not((func3_reg_1178 = ap_const_lv3_5)) and not((func3_reg_1178 = ap_const_lv3_4)) and not((func3_reg_1178 = ap_const_lv3_1)) and not((func3_reg_1178 = ap_const_lv3_0)) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln155_fu_908_p2 = ap_const_lv1_1)) or ((func3_reg_1178 = ap_const_lv3_2) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or ((func3_reg_1178 = ap_const_lv3_5) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or ((func3_reg_1178 = ap_const_lv3_4) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or 
    ((func3_reg_1178 = ap_const_lv3_1) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or ((func3_reg_1178 = ap_const_lv3_0) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or ((ap_predicate_pred351_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred317_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred313_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred305_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred297_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred289_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred281_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred273_state6 
    = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_pred265_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_pred257_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_pred244_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred236_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred216_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
                res_j_1_reg_350 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    src2_reg_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                if ((icmp_ln95_reg_1220 = ap_const_lv1_0)) then 
                    src2_reg_262 <= imm_5_reg_242;
                elsif ((icmp_ln95_reg_1220 = ap_const_lv1_1)) then 
                    src2_reg_262 <= reg_file_q0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                addr_reg_1251 <= addr_fu_768_p2;
                    ap_predicate_pred257_state6 <= (((funcx_reg_1185 = ap_const_lv10_105) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_105) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred265_state6 <= (((funcx_reg_1185 = ap_const_lv10_5) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_5) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred273_state6 <= (((funcx_reg_1185 = ap_const_lv10_1) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_1) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred445_state6 <= (opcode_reg_1163 = ap_const_lv7_23);
                icmp_ln155_reg_1309 <= icmp_ln155_fu_908_p2;
                pc_2_reg_1267 <= pc_2_fu_782_p2;
                res_10_reg_1328 <= res_10_fu_973_p2;
                res_8_reg_1338 <= res_8_fu_983_p2;
                res_9_reg_1333 <= res_9_fu_978_p2;
                trunc_ln99_reg_1257 <= trunc_ln99_fu_773_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                    ap_predicate_pred216_state5 <= (opcode_reg_1163 = ap_const_lv7_17);
                    ap_predicate_pred220_state5 <= (opcode_reg_1163 = ap_const_lv7_67);
                    ap_predicate_pred224_state5 <= (opcode_reg_1163 = ap_const_lv7_6F);
                    ap_predicate_pred236_state5 <= (((funcx_reg_1185 = ap_const_lv10_3) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_3) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred244_state5 <= (((funcx_reg_1185 = ap_const_lv10_2) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_2) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred281_state5 <= (((funcx_reg_1185 = ap_const_lv10_70) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_70) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred289_state5 <= (((funcx_reg_1185 = ap_const_lv10_60) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_60) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred297_state5 <= (((funcx_reg_1185 = ap_const_lv10_40) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_40) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred305_state5 <= (((funcx_reg_1185 = ap_const_lv10_100) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_100) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred313_state5 <= (((funcx_reg_1185 = ap_const_lv10_0) and (opcode_reg_1163 = ap_const_lv7_13)) or ((funcx_reg_1185 = ap_const_lv10_0) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred317_state5 <= (opcode_reg_1163 = ap_const_lv7_37);
                    ap_predicate_pred351_state5 <= ((not((funcx_reg_1185 = ap_const_lv10_0)) and not((funcx_reg_1185 = ap_const_lv10_100)) and not((funcx_reg_1185 = ap_const_lv10_40)) and not((funcx_reg_1185 = ap_const_lv10_60)) and not((funcx_reg_1185 = ap_const_lv10_70)) and not((funcx_reg_1185 = ap_const_lv10_1)) and not((funcx_reg_1185 = ap_const_lv10_5)) and not((funcx_reg_1185 = ap_const_lv10_105)) and not((funcx_reg_1185 = ap_const_lv10_2)) and not((funcx_reg_1185 = ap_const_lv10_3)) and (opcode_reg_1163 = ap_const_lv7_13)) or (not((funcx_reg_1185 = ap_const_lv10_0)) and not((funcx_reg_1185 = ap_const_lv10_100)) and not((funcx_reg_1185 = ap_const_lv10_40)) and not((funcx_reg_1185 = ap_const_lv10_60)) and not((funcx_reg_1185 = ap_const_lv10_70)) and not((funcx_reg_1185 = ap_const_lv10_1)) and not((funcx_reg_1185 = ap_const_lv10_5)) and not((funcx_reg_1185 = ap_const_lv10_105)) and not((funcx_reg_1185 = ap_const_lv10_2)) and not((funcx_reg_1185 = ap_const_lv10_3)) and (opcode_reg_1163 = ap_const_lv7_33)));
                    ap_predicate_pred355_state5 <= (opcode_reg_1163 = ap_const_lv7_3);
                    ap_predicate_pred385_state5 <= (((func3_reg_1178 = ap_const_lv3_3) and (opcode_reg_1163 = ap_const_lv7_63)) or ((func3_reg_1178 = ap_const_lv3_2) and (opcode_reg_1163 = ap_const_lv7_63)));
                    ap_predicate_pred392_state5 <= ((func3_reg_1178 = ap_const_lv3_7) and (opcode_reg_1163 = ap_const_lv7_63));
                    ap_predicate_pred399_state5 <= ((func3_reg_1178 = ap_const_lv3_6) and (opcode_reg_1163 = ap_const_lv7_63));
                    ap_predicate_pred404_state5 <= ((func3_reg_1178 = ap_const_lv3_5) and (opcode_reg_1163 = ap_const_lv7_63));
                    ap_predicate_pred409_state5 <= ((func3_reg_1178 = ap_const_lv3_4) and (opcode_reg_1163 = ap_const_lv7_63));
                    ap_predicate_pred414_state5 <= ((func3_reg_1178 = ap_const_lv3_1) and (opcode_reg_1163 = ap_const_lv7_63));
                    ap_predicate_pred419_state5 <= ((func3_reg_1178 = ap_const_lv3_0) and (opcode_reg_1163 = ap_const_lv7_63));
                    ap_predicate_pred445_state5 <= (opcode_reg_1163 = ap_const_lv7_23);
                    ap_predicate_pred567_state5 <= ((func3_reg_1178 = ap_const_lv3_2) and (opcode_reg_1163 = ap_const_lv7_23));
                    ap_predicate_pred572_state5 <= ((func3_reg_1178 = ap_const_lv3_1) and (opcode_reg_1163 = ap_const_lv7_23));
                    ap_predicate_pred577_state5 <= ((func3_reg_1178 = ap_const_lv3_0) and (opcode_reg_1163 = ap_const_lv7_23));
                src1_reg_1229 <= reg_file_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                func3_reg_1178 <= mem_q0(14 downto 12);
                funcx_reg_1185 <= funcx_fu_526_p3;
                icmp_ln95_reg_1220 <= icmp_ln95_fu_757_p2;
                opcode_reg_1163 <= opcode_fu_468_p1;
                rd_reg_1172 <= mem_q0(11 downto 7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                pc_1_reg_1149 <= pc_fu_166;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, opcode_reg_1163, icmp_ln155_reg_1309, ap_CS_fsm_state6, or_ln13_1_fu_1110_p2, icmp_ln256_fu_1123_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (((((((((((((((((((opcode_reg_1163 = ap_const_lv7_33) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0)) or ((opcode_reg_1163 = ap_const_lv7_33) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_17) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_17) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_37) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_37) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_6F) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_6F) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_63) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_63) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_23) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 
    = ap_const_lv7_23) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_67) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_67) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_3) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_3) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_13) and (icmp_ln256_fu_1123_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_13) and (or_ln13_1_fu_1110_p2 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (((opcode_reg_1163 = ap_const_lv7_3) and (icmp_ln155_reg_1309 = ap_const_lv1_0)) or (not((opcode_reg_1163 = ap_const_lv7_23)) and not((opcode_reg_1163 = ap_const_lv7_63)) and not((opcode_reg_1163 = ap_const_lv7_3)) and not((opcode_reg_1163 = ap_const_lv7_37)) and not((opcode_reg_1163 = ap_const_lv7_13)) and not((opcode_reg_1163 = ap_const_lv7_33)) and not((opcode_reg_1163 = ap_const_lv7_6F)) and not((opcode_reg_1163 = ap_const_lv7_67)) and not((opcode_reg_1163 = ap_const_lv7_17)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    addr_fu_768_p2 <= std_logic_vector(unsigned(src1_reg_1229) + unsigned(imm_5_reg_242));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_condition_199_assign_proc : process(opcode_fu_468_p1)
    begin
                ap_condition_199 <= (not((opcode_fu_468_p1 = ap_const_lv7_17)) and not((opcode_fu_468_p1 = ap_const_lv7_37)) and not((opcode_fu_468_p1 = ap_const_lv7_67)) and not((opcode_fu_468_p1 = ap_const_lv7_3)) and not((opcode_fu_468_p1 = ap_const_lv7_13)) and not((opcode_fu_468_p1 = ap_const_lv7_23)) and not((opcode_fu_468_p1 = ap_const_lv7_63)) and not((opcode_fu_468_p1 = ap_const_lv7_6F)));
    end process;


    ap_condition_204_assign_proc : process(opcode_fu_468_p1)
    begin
                ap_condition_204 <= ((opcode_fu_468_p1 = ap_const_lv7_13) or ((opcode_fu_468_p1 = ap_const_lv7_67) or (opcode_fu_468_p1 = ap_const_lv7_3)));
    end process;


    ap_condition_427_assign_proc : process(opcode_reg_1163, func3_reg_1178, icmp_ln155_reg_1309)
    begin
                ap_condition_427 <= ((func3_reg_1178 = ap_const_lv3_2) and (opcode_reg_1163 = ap_const_lv7_3) and (icmp_ln155_reg_1309 = ap_const_lv1_1));
    end process;


    ap_condition_431_assign_proc : process(opcode_reg_1163, func3_reg_1178, icmp_ln155_reg_1309)
    begin
                ap_condition_431 <= ((func3_reg_1178 = ap_const_lv3_5) and (opcode_reg_1163 = ap_const_lv7_3) and (icmp_ln155_reg_1309 = ap_const_lv1_1));
    end process;


    ap_condition_435_assign_proc : process(opcode_reg_1163, func3_reg_1178, icmp_ln155_reg_1309)
    begin
                ap_condition_435 <= ((func3_reg_1178 = ap_const_lv3_4) and (opcode_reg_1163 = ap_const_lv7_3) and (icmp_ln155_reg_1309 = ap_const_lv1_1));
    end process;


    ap_condition_439_assign_proc : process(opcode_reg_1163, func3_reg_1178, icmp_ln155_reg_1309)
    begin
                ap_condition_439 <= ((func3_reg_1178 = ap_const_lv3_1) and (opcode_reg_1163 = ap_const_lv7_3) and (icmp_ln155_reg_1309 = ap_const_lv1_1));
    end process;


    ap_condition_443_assign_proc : process(opcode_reg_1163, func3_reg_1178, icmp_ln155_reg_1309)
    begin
                ap_condition_443 <= ((func3_reg_1178 = ap_const_lv3_0) and (opcode_reg_1163 = ap_const_lv7_3) and (icmp_ln155_reg_1309 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_res_2_phi_fu_277_p58_assign_proc : process(mem_q0, res_10_reg_1328, res_9_reg_1333, res_8_reg_1338, res_2_reg_273, ap_CS_fsm_state6, ap_predicate_pred257_state6, ap_predicate_pred265_state6, ap_predicate_pred273_state6, zext_ln171_fu_1022_p1, zext_ln168_fu_1031_p1, sext_ln165_fu_1040_p1, sext_ln162_fu_1049_p1, ap_condition_427, ap_condition_431, ap_condition_435, ap_condition_439, ap_condition_443)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
            if ((ap_const_boolean_1 = ap_condition_443)) then 
                ap_phi_mux_res_2_phi_fu_277_p58 <= sext_ln162_fu_1049_p1;
            elsif ((ap_const_boolean_1 = ap_condition_439)) then 
                ap_phi_mux_res_2_phi_fu_277_p58 <= sext_ln165_fu_1040_p1;
            elsif ((ap_const_boolean_1 = ap_condition_435)) then 
                ap_phi_mux_res_2_phi_fu_277_p58 <= zext_ln168_fu_1031_p1;
            elsif ((ap_const_boolean_1 = ap_condition_431)) then 
                ap_phi_mux_res_2_phi_fu_277_p58 <= zext_ln171_fu_1022_p1;
            elsif ((ap_const_boolean_1 = ap_condition_427)) then 
                ap_phi_mux_res_2_phi_fu_277_p58 <= mem_q0;
            elsif ((ap_predicate_pred273_state6 = ap_const_boolean_1)) then 
                ap_phi_mux_res_2_phi_fu_277_p58 <= res_8_reg_1338;
            elsif ((ap_predicate_pred265_state6 = ap_const_boolean_1)) then 
                ap_phi_mux_res_2_phi_fu_277_p58 <= res_9_reg_1333;
            elsif ((ap_predicate_pred257_state6 = ap_const_boolean_1)) then 
                ap_phi_mux_res_2_phi_fu_277_p58 <= res_10_reg_1328;
            else 
                ap_phi_mux_res_2_phi_fu_277_p58 <= res_2_reg_273;
            end if;
        else 
            ap_phi_mux_res_2_phi_fu_277_p58 <= res_2_reg_273;
        end if; 
    end process;


    ap_phi_mux_res_j_1_phi_fu_354_p58_assign_proc : process(opcode_reg_1163, func3_reg_1178, icmp_ln155_reg_1309, ap_CS_fsm_state6, ap_predicate_pred257_state6, ap_predicate_pred265_state6, ap_predicate_pred273_state6, res_j_1_reg_350)
    begin
        if ((((func3_reg_1178 = ap_const_lv3_2) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or ((func3_reg_1178 = ap_const_lv3_5) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or ((func3_reg_1178 = ap_const_lv3_4) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or ((func3_reg_1178 = ap_const_lv3_1) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or ((func3_reg_1178 = ap_const_lv3_0) and (opcode_reg_1163 = ap_const_lv7_3) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln155_reg_1309 = ap_const_lv1_1)) or ((ap_predicate_pred273_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_pred265_state6 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_predicate_pred257_state6 
    = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            ap_phi_mux_res_j_1_phi_fu_354_p58 <= ap_const_lv32_0;
        else 
            ap_phi_mux_res_j_1_phi_fu_354_p58 <= res_j_1_reg_350;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    func3_fu_496_p3 <= mem_q0(14 downto 12);
    func7_1_fu_518_p3 <= 
        func7_fu_504_p3 when (icmp_ln47_fu_512_p2(0) = '1') else 
        ap_const_lv7_0;
    func7_fu_504_p3 <= mem_q0(31 downto 25);
    funcx_fu_526_p3 <= (func7_1_fu_518_p3 & func3_fu_496_p3);
    grp_fu_435_p2 <= "1" when (unsigned(src1_reg_1229) < unsigned(src2_reg_262)) else "0";
    grp_fu_440_p2 <= "1" when (signed(src1_reg_1229) < signed(src2_reg_262)) else "0";
    icmp_ln13_1_fu_1094_p2 <= "1" when (opcode_reg_1163 = ap_const_lv7_67) else "0";
    icmp_ln13_2_fu_1105_p2 <= "1" when (opcode_reg_1163 = ap_const_lv7_63) else "0";
    icmp_ln13_fu_1089_p2 <= "1" when (opcode_reg_1163 = ap_const_lv7_6F) else "0";
    icmp_ln155_fu_908_p2 <= "1" when (trunc_ln99_fu_773_p1 = ap_const_lv2_0) else "0";
    icmp_ln198_fu_886_p2 <= "1" when (src1_reg_1229 = src2_reg_262) else "0";
    icmp_ln201_fu_873_p2 <= "0" when (src1_reg_1229 = src2_reg_262) else "1";
    icmp_ln244_fu_1061_p2 <= "1" when (trunc_ln99_reg_1257 = ap_const_lv2_0) else "0";
    icmp_ln251_fu_1080_p2 <= "1" when (rd_reg_1172 = ap_const_lv5_0) else "0";
    icmp_ln256_fu_1123_p2 <= "0" when (trunc_ln256_fu_1120_p1 = ap_const_lv2_0) else "1";
    icmp_ln47_fu_512_p2 <= "1" when (opcode_fu_468_p1 = ap_const_lv7_33) else "0";
    icmp_ln95_fu_757_p2 <= "1" when (or_ln_fu_747_p4 = ap_const_lv7_33) else "0";
    imm12_fu_787_p2 <= std_logic_vector(shift_left(unsigned(imm_5_reg_242),to_integer(unsigned('0' & ap_const_lv32_C(31-1 downto 0)))));
    immI_fu_534_p4 <= mem_q0(31 downto 20);
    immS_fu_584_p3 <= (tmp_2_fu_564_p4 & tmp_3_fu_574_p4);
    imm_2_fu_614_p6 <= ((((tmp_4_fu_606_p3 & tmp_fu_548_p3) & tmp_5_fu_596_p4) & tmp_1_fu_556_p3) & ap_const_lv1_0);
    imm_3_fu_656_p17 <= (((((((((((((((tmp_4_fu_606_p3 & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_4_fu_606_p3) & tmp_9_fu_648_p3) & tmp_6_fu_640_p3) & tmp_s_fu_632_p3) & ap_const_lv1_0);
    imm_4_fu_700_p3 <= (tmp_7_fu_692_p3 & ap_const_lv12_0);
    lshr_ln1_fu_914_p4 <= addr_fu_768_p2(11 downto 2);
    lshr_ln2_fu_1066_p4 <= addr_reg_1251(11 downto 2);
    lshr_ln_fu_453_p4 <= pc_fu_166(11 downto 2);
    mem_address0 <= mem_address0_local;

    mem_address0_local_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state6, zext_ln34_fu_463_p1, zext_ln159_fu_924_p1, zext_ln248_fu_1075_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            mem_address0_local <= zext_ln248_fu_1075_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mem_address0_local <= zext_ln159_fu_924_p1(10 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mem_address0_local <= zext_ln34_fu_463_p1(10 - 1 downto 0);
        else 
            mem_address0_local <= "XXXXXXXXXX";
        end if; 
    end process;

    mem_ce0 <= mem_ce0_local;

    mem_ce0_local_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            mem_ce0_local <= ap_const_logic_1;
        else 
            mem_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mem_d0 <= ap_phi_mux_res_2_phi_fu_277_p58;
    mem_we0 <= mem_we0_local;

    mem_we0_local_assign_proc : process(opcode_reg_1163, ap_CS_fsm_state6, icmp_ln244_fu_1061_p2)
    begin
        if (((opcode_reg_1163 = ap_const_lv7_23) and (icmp_ln244_fu_1061_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            mem_we0_local <= ap_const_logic_1;
        else 
            mem_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    opcode_fu_468_p1 <= mem_q0(7 - 1 downto 0);
    or_ln13_1_fu_1110_p2 <= (or_ln13_fu_1099_p2 or icmp_ln13_2_fu_1105_p2);
    or_ln13_fu_1099_p2 <= (icmp_ln13_fu_1089_p2 or icmp_ln13_1_fu_1094_p2);
    or_ln_fu_747_p4 <= ((tmp_8_fu_733_p4 & ap_const_lv1_1) & trunc_ln95_fu_743_p1);
    pc_2_fu_782_p2 <= std_logic_vector(unsigned(pc_1_reg_1149) + unsigned(ap_const_lv32_4));

    pstrb_assign_proc : process(ap_CS_fsm_state5, ap_predicate_pred567_state5, ap_predicate_pred572_state5, ap_predicate_pred577_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
            if ((ap_predicate_pred577_state5 = ap_const_boolean_1)) then 
                pstrb <= ap_const_lv4_1;
            elsif ((ap_predicate_pred572_state5 = ap_const_boolean_1)) then 
                pstrb <= ap_const_lv4_3;
            elsif ((ap_predicate_pred567_state5 = ap_const_boolean_1)) then 
                pstrb <= ap_const_lv4_F;
            else 
                pstrb <= "XXXX";
            end if;
        else 
            pstrb <= "XXXX";
        end if; 
    end process;


    pstrb_ap_vld_assign_proc : process(ap_CS_fsm_state5, ap_predicate_pred567_state5, ap_predicate_pred572_state5, ap_predicate_pred577_state5)
    begin
        if ((((ap_predicate_pred577_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred572_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_predicate_pred567_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            pstrb_ap_vld <= ap_const_logic_1;
        else 
            pstrb_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_address0 <= reg_file_address0_local;

    reg_file_address0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state6, zext_ln95_fu_763_p1, zext_ln252_fu_1085_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_address0_local <= zext_ln252_fu_1085_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            reg_file_address0_local <= zext_ln95_fu_763_p1(5 - 1 downto 0);
        else 
            reg_file_address0_local <= "XXXXX";
        end if; 
    end process;

    reg_file_address1 <= zext_ln94_fu_728_p1(5 - 1 downto 0);
    reg_file_ce0 <= reg_file_ce0_local;

    reg_file_ce0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            reg_file_ce0_local <= ap_const_logic_1;
        else 
            reg_file_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_ce1 <= reg_file_ce1_local;

    reg_file_ce1_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            reg_file_ce1_local <= ap_const_logic_1;
        else 
            reg_file_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_d0 <= ap_phi_mux_res_2_phi_fu_277_p58;
    reg_file_we0 <= reg_file_we0_local;

    reg_file_we0_local_assign_proc : process(opcode_reg_1163, icmp_ln155_reg_1309, ap_CS_fsm_state6, icmp_ln251_fu_1080_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and ((((((((opcode_reg_1163 = ap_const_lv7_33) and (icmp_ln251_fu_1080_p2 = ap_const_lv1_0)) or ((opcode_reg_1163 = ap_const_lv7_17) and (icmp_ln251_fu_1080_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_37) and (icmp_ln251_fu_1080_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_6F) and (icmp_ln251_fu_1080_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_67) and (icmp_ln251_fu_1080_p2 = ap_const_lv1_0))) or ((opcode_reg_1163 = ap_const_lv7_3) and (icmp_ln251_fu_1080_p2 = ap_const_lv1_0) and (icmp_ln155_reg_1309 = ap_const_lv1_1))) or ((opcode_reg_1163 = ap_const_lv7_13) and (icmp_ln251_fu_1080_p2 = ap_const_lv1_0))))) then 
            reg_file_we0_local <= ap_const_logic_1;
        else 
            reg_file_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    res_10_fu_973_p2 <= std_logic_vector(shift_right(signed(src1_reg_1229),to_integer(unsigned('0' & src2_reg_262(31-1 downto 0)))));
    res_13_fu_1045_p1 <= mem_q0(8 - 1 downto 0);
    res_14_fu_1036_p1 <= mem_q0(16 - 1 downto 0);
    res_15_fu_1027_p1 <= mem_q0(8 - 1 downto 0);
    res_16_fu_1018_p1 <= mem_q0(16 - 1 downto 0);
    res_3_fu_1008_p2 <= std_logic_vector(unsigned(src1_reg_1229) + unsigned(src2_reg_262));
    res_4_fu_1003_p2 <= std_logic_vector(unsigned(src1_reg_1229) - unsigned(src2_reg_262));
    res_5_fu_998_p2 <= (src2_reg_262 xor src1_reg_1229);
    res_6_fu_993_p2 <= (src2_reg_262 or src1_reg_1229);
    res_7_fu_988_p2 <= (src2_reg_262 and src1_reg_1229);
    res_8_fu_983_p2 <= std_logic_vector(shift_left(unsigned(src1_reg_1229),to_integer(unsigned('0' & src2_reg_262(31-1 downto 0)))));
    res_9_fu_978_p2 <= std_logic_vector(shift_right(unsigned(src1_reg_1229),to_integer(unsigned('0' & src2_reg_262(31-1 downto 0)))));
    res_b_fu_777_p2 <= std_logic_vector(unsigned(imm_5_reg_242) + unsigned(pc_1_reg_1149));
    res_fu_1013_p2 <= std_logic_vector(unsigned(imm12_fu_787_p2) + unsigned(pc_1_reg_1149));
    res_j_3_fu_891_p3 <= 
        res_b_fu_777_p2 when (icmp_ln198_fu_886_p2(0) = '1') else 
        pc_2_fu_782_p2;
    res_j_4_fu_878_p3 <= 
        res_b_fu_777_p2 when (icmp_ln201_fu_873_p2(0) = '1') else 
        pc_2_fu_782_p2;
    res_j_5_fu_865_p3 <= 
        res_b_fu_777_p2 when (grp_fu_440_p2(0) = '1') else 
        pc_2_fu_782_p2;
    res_j_6_fu_857_p3 <= 
        res_b_fu_777_p2 when (xor_ln207_fu_851_p2(0) = '1') else 
        pc_2_fu_782_p2;
    res_j_7_fu_843_p3 <= 
        res_b_fu_777_p2 when (grp_fu_435_p2(0) = '1') else 
        pc_2_fu_782_p2;
    res_j_8_fu_835_p3 <= 
        res_b_fu_777_p2 when (xor_ln213_fu_829_p2(0) = '1') else 
        pc_2_fu_782_p2;
    rs1_fu_480_p3 <= mem_q0(19 downto 15);
    rs2_fu_488_p3 <= mem_q0(24 downto 20);
    select_ln256_fu_1129_p3 <= 
        pc_1_reg_1149 when (icmp_ln256_fu_1123_p2(0) = '1') else 
        ap_phi_mux_res_j_1_phi_fu_354_p58;
        sext_ln162_fu_1049_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_13_fu_1045_p1),32));

        sext_ln165_fu_1040_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_14_fu_1036_p1),32));

        sext_ln53_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(immI_fu_534_p4),32));

        sext_ln55_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(immS_fu_584_p3),32));

        sext_ln57_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(imm_2_fu_614_p6),32));

    tmp_1_fu_556_p3 <= mem_q0(11 downto 8);
    tmp_2_fu_564_p4 <= mem_q0(31 downto 25);
    tmp_3_fu_574_p4 <= mem_q0(11 downto 7);
    tmp_4_fu_606_p3 <= mem_q0(31 downto 31);
    tmp_5_fu_596_p4 <= mem_q0(30 downto 25);
    tmp_6_fu_640_p3 <= mem_q0(20 downto 20);
    tmp_7_fu_692_p3 <= mem_q0(31 downto 12);
    tmp_8_fu_733_p4 <= mem_q0(6 downto 5);
    tmp_9_fu_648_p3 <= mem_q0(19 downto 12);
    tmp_fu_548_p3 <= mem_q0(7 downto 7);
    tmp_s_fu_632_p3 <= mem_q0(30 downto 21);
    trunc_ln256_fu_1120_p1 <= pc_1_reg_1149(2 - 1 downto 0);
    trunc_ln95_fu_743_p1 <= mem_q0(4 - 1 downto 0);
    trunc_ln99_fu_773_p1 <= addr_fu_768_p2(2 - 1 downto 0);
    xor_ln207_fu_851_p2 <= (grp_fu_440_p2 xor ap_const_lv1_1);
    xor_ln213_fu_829_p2 <= (grp_fu_435_p2 xor ap_const_lv1_1);
    zext_ln146_fu_969_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_440_p2),32));
    zext_ln149_fu_965_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_435_p2),32));
    zext_ln159_fu_924_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_914_p4),64));
    zext_ln168_fu_1031_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_15_fu_1027_p1),32));
    zext_ln171_fu_1022_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_16_fu_1018_p1),32));
    zext_ln248_fu_1075_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_1066_p4),64));
    zext_ln252_fu_1085_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rd_reg_1172),64));
    zext_ln34_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_453_p4),64));
    zext_ln94_fu_728_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rs1_fu_480_p3),64));
    zext_ln95_fu_763_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rs2_fu_488_p3),64));
end behav;
