// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cpu_cpu,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7z010-clg225-1I,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.667000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=467,HLS_SYN_LUT=1709,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module cpu (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mem_address0,
        mem_ce0,
        mem_we0,
        mem_d0,
        mem_q0,
        pstrb
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] mem_address0;
output   mem_ce0;
output   mem_we0;
output  [31:0] mem_d0;
input  [31:0] mem_q0;
output  [3:0] pstrb;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] pstrb;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] reg_file_address0;
reg    reg_file_ce0;
reg    reg_file_we0;
reg   [31:0] reg_file_d0;
wire   [31:0] reg_file_q0;
reg    reg_file_ce1;
wire   [31:0] reg_file_q1;
wire    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start;
wire    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done;
wire    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_idle;
wire    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_ready;
wire   [4:0] grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_address0;
wire    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_ce0;
wire    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_we0;
wire   [31:0] grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_d0;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_idle;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_ready;
wire   [9:0] grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_address0;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_ce0;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_we0;
wire   [31:0] grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_d0;
wire   [4:0] grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address0;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce0;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_we0;
wire   [31:0] grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_d0;
wire   [4:0] grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address1;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce1;
wire   [3:0] grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb;
wire    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb_ap_vld;
reg    grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] pstrb_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg = 1'b0;
#0 grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg = 1'b0;
end

cpu_reg_file_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
reg_file_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(reg_file_address0),
    .ce0(reg_file_ce0),
    .we0(reg_file_we0),
    .d0(reg_file_d0),
    .q0(reg_file_q0),
    .address1(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address1),
    .ce1(reg_file_ce1),
    .q1(reg_file_q1)
);

cpu_cpu_Pipeline_VITIS_LOOP_22_1 grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start),
    .ap_done(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done),
    .ap_idle(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_idle),
    .ap_ready(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_ready),
    .reg_file_address0(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_address0),
    .reg_file_ce0(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_ce0),
    .reg_file_we0(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_we0),
    .reg_file_d0(grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_d0)
);

cpu_cpu_Pipeline_PROGRAM_LOOP grp_cpu_Pipeline_PROGRAM_LOOP_fu_38(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start),
    .ap_done(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done),
    .ap_idle(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_idle),
    .ap_ready(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_ready),
    .mem_address0(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_address0),
    .mem_ce0(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_ce0),
    .mem_we0(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_we0),
    .mem_d0(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_d0),
    .mem_q0(mem_q0),
    .reg_file_address0(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address0),
    .reg_file_ce0(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce0),
    .reg_file_we0(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_we0),
    .reg_file_d0(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_d0),
    .reg_file_q0(reg_file_q0),
    .reg_file_address1(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address1),
    .reg_file_ce1(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce1),
    .reg_file_q1(reg_file_q1),
    .pstrb(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb),
    .pstrb_ap_vld(grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg <= 1'b1;
        end else if ((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_ready == 1'b1)) begin
            grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_ready == 1'b1)) begin
            grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pstrb_reg <= grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        pstrb = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_pstrb;
    end else begin
        pstrb = pstrb_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_address0 = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_address0 = grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_address0;
    end else begin
        reg_file_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_ce0 = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_ce0 = grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_ce0;
    end else begin
        reg_file_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_ce1 = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_ce1;
    end else begin
        reg_file_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_d0 = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_d0 = grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_d0;
    end else begin
        reg_file_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_we0 = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_reg_file_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_we0 = grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_reg_file_we0;
    end else begin
        reg_file_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_ap_start_reg;

assign grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start = grp_cpu_Pipeline_VITIS_LOOP_22_1_fu_32_ap_start_reg;

assign mem_address0 = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_address0;

assign mem_ce0 = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_ce0;

assign mem_d0 = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_d0;

assign mem_we0 = grp_cpu_Pipeline_PROGRAM_LOOP_fu_38_mem_we0;

endmodule //cpu
